### ISSUE TITLE
Staff: PHP error and I'm able to see staff created by other users

### ISSUE THREAD

**Issue by anvarsha** [bosbangkok/Chillireward_web#15]
Steps to reproduce:
1. Add a new staff. After adding in all options of staff it is displaying that added staff
2. Then if click on any alphabet(eg:S) I'm able to see 2 records. i.e., I'm able to staffs created by other user
3. Then again if I click on all option it is displaying PHP error rather than displaying the staff created by that user. 

Please find the attachments
![staff-01](https://cloud.githubusercontent.com/assets/13901526/9440262/46cd217c-4a8b-11e5-9e38-852ebffc73c9.png)
![staff-02](https://cloud.githubusercontent.com/assets/13901526/9440263/46ce41ec-4a8b-11e5-8a9e-e1e55761b691.png)
![staff-03](https://cloud.githubusercontent.com/assets/13901526/9440264/46d1b0d4-4a8b-11e5-8ecf-32d77d39fc2a.png)

**Comment by yaminiverma88** [comment]
Fixed

**Comment by anvarsha** [comment]
Issue is resolved
