### ISSUE TITLE
Rewards : "No promotions available." message to be displayed if there are no promotions when sorted by an alphabet.

### ISSUE THREAD

**Issue by aloktare** [bosbangkok/Chillireward_web#24]
1. Go to Rewards page.
2. Sort by Z
3. If no promotions starting with Z , "No promotions available" to be displayed.
![no promotions available](https://cloud.githubusercontent.com/assets/13728520/9513081/ba52880c-4ca8-11e5-822c-78103d9e659d.png)

**Comment by yaminiverma88** [comment]
Fixed

**Comment by aloktare** [comment]
Verified fixed.
