### ISSUE TITLE
Add Beacon : Help text to be changed.

### ISSUE THREAD

**Issue by aloktare** [bosbangkok/Chillireward_web#25]
Please use the following 

HELP

Register your Beacons here.
1. Specify a name for the beacon.
2. Assign it to a Store.
3. Select the manufacturer.
4. Select the UUID. (You would have received the UUID in an email)
5. Enter correct Major & Minor (Major & Minor are printed on the Beacon)
6. Click Add to register.

When you register the beacons, you can attach promotions to them while creating promotions.

**Comment by yaminiverma88** [comment]
Fixed

**Comment by aloktare** [comment]
Verified fixed.
