### ISSUE TITLE
Button title should be "View Beacons","View Stores","View Staff","View Promotions" on respective Add pages.

### ISSUE THREAD

**Issue by aloktare** [bosbangkok/Chillireward_web#26]
![view beacons](https://cloud.githubusercontent.com/assets/13728520/9513462/071696ce-4cae-11e5-9f60-9ffd37fb9a68.png)
![view rewards](https://cloud.githubusercontent.com/assets/13728520/9513464/072b4a42-4cae-11e5-99b3-45b75da13b80.png)
![view staff](https://cloud.githubusercontent.com/assets/13728520/9513461/0736e424-4cae-11e5-9c62-8d20ee03306c.png)
![view stores](https://cloud.githubusercontent.com/assets/13728520/9513463/072cd894-4cae-11e5-851b-dec46552f9de.png)

**Comment by yaminiverma88** [comment]
fixed

**Comment by aloktare** [comment]
Verified fixed.
