### ISSUE TITLE
Beacon: Add and edit : minor and major fields are displaying wrong data

### ISSUE THREAD

**Issue by anvarsha** [bosbangkok/Chillireward_web#27]
Minor and Major fields are accepting alphabets but displaying as 0

**Comment by anvarsha** [comment]
PFA
![beacon-edit and add](https://cloud.githubusercontent.com/assets/13901526/9514953/bc1194c2-4cbb-11e5-901f-405d89ce8ebb.png)

**Comment by yaminiverma88** [comment]
fixed

**Comment by anvarsha** [comment]
Verified, fixed
