### ISSUE TITLE
Add promotion : "Please enter valid number" error displayed when discount percentage is greater than Current price.

### ISSUE THREAD

**Issue by aloktare** [bosbangkok/Chillireward_web#28]
1. Go to Add promotions.
2. Put discount percentage greater than current price.

eg: Current Price - 50   Discount percentage - 60
![discount percentage](https://cloud.githubusercontent.com/assets/13728520/9545356/8ad54156-4da6-11e5-93c7-d9b245fd3add.png)

**Comment by yaminiverma88** [comment]
Fixed

**Comment by aloktare** [comment]
Verified fixed.
