### ISSUE TITLE
Text changes & UI changes on Rewards page.

### ISSUE THREAD

**Issue by aloktare** [bosbangkok/Chillireward_web#30]
1. Summary to be changed to Description.
2. Terms & Conditions -- Remove & and change to Terms and Conditions.
3. Remove time dropdowns.
4. Remove Select Reward Mode, In App & In Store radio buttons and replace by -

    Beacon promotion
    [_]   I want to publish this promotion in my store using Beacon.
![rewards changes](https://cloud.githubusercontent.com/assets/13728520/9577883/f097854a-5002-11e5-8174-c32aa8233e3d.png)

**Comment by PreetiGupta1989** [comment]
Fixed.

**Comment by aloktare** [comment]
Verified fixed.
