### ISSUE TITLE
Business: Phone - incorrect warning message

### ISSUE THREAD

**Issue by anvarsha** [bosbangkok/Chillireward_web#35]
1. Even though I didn't enter 0 in the beginning it is displaying value can't start from zero. PFA

2. Only max character size limit is provided. I can enter any range of characters(1-10) less than 11

![business- phone no wrong warning message](https://cloud.githubusercontent.com/assets/13901526/9625429/a3c88242-5173-11e5-8846-2ce3b6f65d69.png)
![business- phone number01](https://cloud.githubusercontent.com/assets/13901526/9625430/a3f1000a-5173-11e5-9122-6f8680aaf111.png)

**Comment by yaminiverma88** [comment]
Fixed

**Comment by anvarsha** [comment]
Verified fixed
