### ISSUE TITLE
Business Information Page : PHP error displayed on top of the page.

### ISSUE THREAD

**Issue by aloktare** [bosbangkok/Chillireward_web#4]
![php error](https://cloud.githubusercontent.com/assets/13728520/9329317/0e46cc48-45ce-11e5-92fb-d4ebe5624a12.png)

**Comment by yaminiverma88** [comment]
Fixed

**Comment by aloktare** [comment]
Error appears when business information is not filled.

**Comment by aloktare** [comment]
Verified fixed.
